- name: playbook for debug
  hosts: all
  vars_files:
   - ./varfile
vars_prompt:
- name: URL
  prompt: "Please enter your website"
  private: false
  tasks:
    - name: print hello world
      debug:
        msg: "Please visit {{ URL }}"
    - name: print hello world
      debug:
       msg: "Please visit {{ URL }}"
    - name: print hello world
      debug:
       msg: "Please visit {{ URL }}"
      vars:
        URL: "local.cloudblitz.in"